source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from accounts.views import RegisterView, UserDetailView, UserPasswordChangeView, UserChangeView, AllUserView, UserDelete

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register', RegisterView.as_view(), name='create'),
    path('users/', AllUserView.as_view(), name='users'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/change/', UserChangeView.as_view(), name='change'),
    path('<int:pk>/delete/', UserDelete.as_view(), name='delete'),
    path('<int:pk>/password_change/', UserPasswordChangeView.as_view(), name='password_change')
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api/v1/', include('api_v1.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path, include

from webapp.views import CategoryCreate, Categories, CategoryUpdate, CategoryDelete, CategoryNewsView
from webapp.views.article_views import ArticleView, Articles, ArticleUpdate, ArticleDelete, ArticleCreate
from webapp.views.main_category import MainCategoryCreate, MainCategories, MainCategoryView, MainCategoryUpdate, \
    MainCategoryDelete

app_name = 'webapp'

urlpatterns = [
    path('articles/', Articles.as_view(), name='articles_view'),
    path('article/create', ArticleCreate.as_view(), name='article_create'),
    path('article/<int:pk>/', ArticleView.as_view(), name='article_view'),
    path('article/<int:pk>/update', ArticleUpdate.as_view(), name='article_update'),
    path('article/<int:pk>/delete', ArticleDelete.as_view(), name='article_delete'),

    path('categories/', Categories.as_view(), name='categories_view'),
    path('category/create', CategoryCreate.as_view(), name='category_create'),
    path('category/<int:pk>/', CategoryNewsView.as_view(), name='category_news'),
    path('category/<int:pk>/update', CategoryUpdate.as_view(), name='category_update'),
    path('category/<int:pk>/delete', CategoryDelete.as_view(), name='category_delete'),

    path('', MainCategories.as_view(), name='main_categories_view'),
    path('main_category/create', MainCategoryCreate.as_view(), name='main_category_create'),
    path('main_category/<int:pk>/', MainCategoryView.as_view(), name='main_category_view'),
    path('main_category/<int:pk>/update', MainCategoryUpdate.as_view(), name='main_category_update'),
    path('main_category/<int:pk>/delete', MainCategoryDelete.as_view(), name='main_category_delete'),

 ]

source/accounts/models.py
from django.db import models

# Create your models here.

source/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms


class MyUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ['username', 'password1', 'password2',
                  'first_name', 'last_name', 'email']


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'last_name', 'email']
        labels = {'username': 'Ник', 'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class SetPasswordForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm']


class PasswordChangeForm(SetPasswordForm):
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from django.contrib.auth import login, get_user_model
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, ListView, DeleteView

from accounts.forms import MyUserCreationForm, PasswordChangeForm, UserChangeForm


class AllUserView(LoginRequiredMixin, ListView):
    template_name = 'all_users.html'
    model = User


class RegisterView(CreateView):
    model = User
    template_name = 'user_create.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('index')
        return next_url


class UserDetailView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'


class UserPasswordChangeView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    template_name = 'user_password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def test_func(self):
        return self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('accounts:login')


class UserChangeView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'

    def test_func(self):
        return self.get_object() == self.request.user

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})


class UserDelete(PermissionRequiredMixin, DeleteView):
    template_name = 'user_delete.html'
    model = User
    success_url = reverse_lazy('accounts:users')
    permission_required = 'auth.delete_user'

source/accounts/templates/all_users.html
{% extends 'base.html' %}

{% block title %}Articles{% endblock %}

{% block menu %}
    {% if user.is_authenticated %}
        <a class="text-white text-center px-3"  href="{% url 'webapp:main_categories_view' %}" >На главную</a>
    {% endif %}
{% endblock %}

<h1 class="word">All Users:</h1>
{% block content %}
    <h3 class="word text-center">All Users:</h3>
    <div class="box">
        {% for user in user_list %}
            <div class="table">
                <div class="cell text-left">
                    <h5><a href="{% url 'accounts:detail' user.pk %}">№{{ user.pk }}. {{ user.get_username }}</a></h5>
                </div>
                <div class="cell text-right">
                    {% if user == request.user %}
                        <a href="{% url 'accounts:change' user.pk %}" ><button type="button"  class="btn btn-success">Update</button></a>
                    {% endif %}
                    {% if perms.auth.delete_user %}
                        <a href="{% url 'accounts:delete' user.pk %}" ><button type="button"  class="btn btn-danger">Delete. </button></a>
                    {% endif %}
                </div>
            </div>
            <hr>
        {% endfor %}
    </div>
{% endblock %}

source/accounts/templates/user_change.html
{% extends 'base.html' %}

{% block title %}Редактировать пользователя{% endblock %}

{% block menu %}
    {% if user.is_authenticated %}
        <a class="text-white text-center px-3"  href="{% url 'webapp:main_categories_view' %}" >На главную</a>
        <a class="text-white text-center px-3" href="{% url "accounts:detail" user_obj.pk %}">Назад </a>
        {% if request.user == user_obj %}
            <a class="text-white text-center px-3" href="{% url "accounts:password_change" user_obj.pk %}">Смена пароля</a>
        {% endif %}
    {% endif %}
{% endblock %}

{% block content %}
    <h1 class="ml-5 pt-5">Поменять личные данные</h1>
    <form action="{% url 'accounts:change' user_obj.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partial/form.html' with form=form fields_only=True %}
        <br>
        <input type="submit" class="btn btn-primary mb-2" value="Submit">
    </form>
{% endblock %}

source/accounts/templates/user_create.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block menu %}
     {% if user.is_authenticated %}
        <a class="text-white text-center px-3" href="{% url 'webapp:main_categories_view' %}">На главную</a>
    {% endif %}
{% endblock %}

{% block content %}
    <h1 class="mt-5 pt-5">Регистрация</h1>
    {% include 'partial/form.html' with form_method='post' button_text="Зарегистрироваться" %}
{% endblock %}

source/accounts/templates/user_delete.html
{% extends "base.html" %}

{% block title %}Удаление статьи{% endblock %}

{% block menu %}
     {% if user.is_authenticated %}
        <a class="text-white text-center px-3" href="{% url 'webapp:main_categories_view' %}">На главную</a>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="coL col-lg-12 mt-5">
        <h1 class="pt-4">Вы действительно хотите удалить пользователя: # <b class="text-primary">{{ user.get_username}}</b> ?</h1>
    </div>
    <div class="row">
        <form method="POST" action="{% url "accounts:delete" user.pk %}" class="text-center">
            {% csrf_token %}
        <div class="coL col-lg-3 ml-5 mt-1">
            {% if perms.auth.delete_user %}
                <a href="{% url "accounts:delete" user.pk %}" >
                    <button type="submit"  class="btn btn-danger">Delete</button>
                </a>
            {% endif %}
        </div>
        </form>
        <div class="coL col-lg-3  mt-1">
            <a href="{% url 'accounts:users' %}" >
                <button type="submit"  class="btn btn-primary">Отмена</button>
            </a>
        </div>
    </div>

{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}

{% block title %}Пользователь{% endblock %}

{% block menu %}
    {% if user.is_authenticated %}
        <a class="text-white text-center px-3" href="{% url 'webapp:main_categories_view' %}">На главную</a>
        {% if request.user == user_obj %}
            <a class="text-white text-center px-3" href="{% url 'accounts:change' user_obj.pk %}">Редактирование личных данных</a>
            <a class="text-white text-center px-3" href="{% url "accounts:password_change" user_obj.pk %}">Смена пароля</a>
        {% endif %}
    {% endif %}

{% endblock %}

{% block content %}
    <div class="box">
        <h1 class="ml-5 pt-5">Личная страница пользователя {{ user_obj.get_full_name|default:user_obj.username }}</h1>
        <p>Login: {{ user.username }}</p>
        <p>Имя: {{ user.first_name }}</p>
        <p>Фамилия: {{ user.last_name }}</p>
        <p>Почта: {{ user_obj.email }}</p>
    </div>
{% endblock %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}

{% block title %}Смена пароля{% endblock %}

{% block menu %}
    {% if user.is_authenticated %}
        <a class="text-white text-center px-3"  href="{% url 'webapp:main_categories_view' %}" >На главную</a>
        <a class="text-white text-center px-3" href="{% url "accounts:detail" user_obj.pk %}">Назад</a>
        {% if request.user == user_obj %}
            <a class="text-white text-center px-3" href="{% url "accounts:change" user_obj.pk %}">Редактирование личных данных</a>
        {% endif %}
    {% endif %}
{% endblock %}

{% block content %}
    <h1 class="ml-1 mt-5 pt-5">Смена пароля</h1>
    {% url "accounts:password_change" user_obj.pk as action_url %}
    {% include 'partial/form.html' with action_url=action_url form_method="post" %}
{% endblock %}