source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from accounts.views import RegisterView, UserDetailView, UserPasswordChangeView, UserChangeView, AllUserView, UserDelete

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register', RegisterView.as_view(), name='create'),
    path('users/', AllUserView.as_view(), name='users'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/change/', UserChangeView.as_view(), name='change'),
    path('<int:pk>/delete/', UserDelete.as_view(), name='delete'),
    path('<int:pk>/password_change/', UserPasswordChangeView.as_view(), name='password_change')
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api/v1/', include('api_v1.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path, include

from webapp.views import CategoryCreate, Categories, CategoryUpdate, CategoryDelete, CategoryNewsView
from webapp.views.article_views import ArticleView, Articles, ArticleUpdate, ArticleDelete, ArticleCreate
from webapp.views.main_category import MainCategoryCreate, MainCategories, MainCategoryView, MainCategoryUpdate, \
    MainCategoryDelete

app_name = 'webapp'

urlpatterns = [
    path('articles/', Articles.as_view(), name='articles_view'),
    path('article/create', ArticleCreate.as_view(), name='article_create'),
    path('article/<int:pk>/', ArticleView.as_view(), name='article_view'),
    path('article/<int:pk>/update', ArticleUpdate.as_view(), name='article_update'),
    path('article/<int:pk>/delete', ArticleDelete.as_view(), name='article_delete'),

    path('categories/', Categories.as_view(), name='categories_view'),
    path('category/create', CategoryCreate.as_view(), name='category_create'),
    path('category/<int:pk>/', CategoryNewsView.as_view(), name='category_news'),
    path('category/<int:pk>/update', CategoryUpdate.as_view(), name='category_update'),
    path('category/<int:pk>/delete', CategoryDelete.as_view(), name='category_delete'),

    path('', MainCategories.as_view(), name='main_categories_view'),
    path('main_category/create', MainCategoryCreate.as_view(), name='main_category_create'),
    path('main_category/<int:pk>/', MainCategoryView.as_view(), name='main_category_view'),
    path('main_category/<int:pk>/update', MainCategoryUpdate.as_view(), name='main_category_update'),
    path('main_category/<int:pk>/delete', MainCategoryDelete.as_view(), name='main_category_delete'),

 ]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок',)
    description = models.TextField(max_length=3000, verbose_name='Описание')
    category_id = models.ManyToManyField('webapp.Category', related_name='articles',
                                         verbose_name='Категория')
    user_id = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT, default=1,
                                related_name='articles', verbose_name='Пользователь')
    image = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Фото')

    def __str__(self):
        return "{}. {}".format(self.pk, self.title)

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class MainCategory(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок', )

    def __str__(self):
        return "{}. {}".format(self.pk, self.title)

    class Meta:
        verbose_name = 'Main_category'
        verbose_name_plural = 'Main_categories'


class Category(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок',)
    parent_id = models.ForeignKey('webapp.MainCategory', on_delete=models.PROTECT, null=False, blank=False,
                                  verbose_name='Main category')

    def __str__(self):
        return "{}. {}".format(self.pk, self.title)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

source/webapp/forms.py
from django import forms

from webapp.models import Article, Category, MainCategory


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'description', 'category_id', 'image']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['title', 'parent_id']


class MainCategoryForm(forms.ModelForm):
    class Meta:
        model = MainCategory
        fields = ['title']

source/webapp/views/article_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView, UpdateView, DeleteView, CreateView

from webapp.forms import ArticleForm
from webapp.models import Article


class ArticleCreate(LoginRequiredMixin, CreateView):
    model = Article
    template_name = 'article/article_create.html'
    form_class = ArticleForm

    def form_valid(self, form):
        article = form.save(commit=False)
        article.user_id = self.request.user
        article.save()
        form.save_m2m()
        return redirect('webapp:article_view', pk=article.pk)


class ArticleView(LoginRequiredMixin, DetailView):
    template_name = 'article/article.html'
    model = Article


class Articles(LoginRequiredMixin, ListView):
    template_name = 'article/articles_view.html'
    context_object_name = 'articles'
    model = Article


class ArticleUpdate(PermissionRequiredMixin, UpdateView):
    template_name = 'article/article_update.html'
    form_class = ArticleForm
    model = Article
    permission_required = 'webapp.change_article'

    def get_success_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.object.pk})


class ArticleDelete(PermissionRequiredMixin, DeleteView):
    template_name = 'article/article_delete.html'
    model = Article
    success_url = reverse_lazy('webapp:articles_view')
    permission_required = 'webapp.delete_article'

source/webapp/views/category.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView, UpdateView, DeleteView, CreateView

from webapp.forms import CategoryForm
from webapp.models import Category, Article


class CategoryCreate(LoginRequiredMixin, CreateView):
    model = Category
    template_name = 'category/category_create.html'
    form_class = CategoryForm

    def form_valid(self, form):
        category = form.save(commit=False)
        category.save()
        return redirect('webapp:category_news', pk=category.pk)


class CategoryNewsView(LoginRequiredMixin, DetailView):
    template_name = 'category/category_news.html'
    model = Category

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        category = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        articles = Article.objects.filter(category_id=category.pk)
        context['articles'] = articles
        context['category'] = category
        return context


class Categories(LoginRequiredMixin, ListView):
    template_name = 'category/categories_view.html'
    model = Category


class CategoryUpdate(PermissionRequiredMixin, UpdateView):
    template_name = 'category/category_update.html'
    form_class = CategoryForm
    model = Category
    permission_required = 'webapp.change_category'

    def get_success_url(self):
        return reverse('webapp:category_news', kwargs={'pk': self.object.pk})


class CategoryDelete(PermissionRequiredMixin, DeleteView):
    template_name = 'category/category_delete.html'
    model = Category
    success_url = reverse_lazy('webapp:categories_view')
    permission_required = 'webapp.delete_category'

source/webapp/views/main_category.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView, UpdateView, DeleteView, CreateView

from webapp.forms import MainCategoryForm
from webapp.models import Category, MainCategory


class MainCategoryCreate(LoginRequiredMixin, CreateView):
    model = MainCategory
    template_name = 'main_category/create_main_category.html'
    form_class = MainCategoryForm

    def form_valid(self, form):
        category = form.save(commit=False)
        category.save()
        return redirect('webapp:main_category_view', pk=category.pk)


class MainCategoryView(LoginRequiredMixin, DetailView):
    template_name = 'main_category/one_main_category.html'
    model = MainCategory

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        main_category = get_object_or_404(MainCategory, pk=self.kwargs.get('pk'))
        categories = Category.objects.filter(parent_id=main_category.pk)
        context['categories'] = categories
        context['main_category'] = main_category
        return context


class MainCategories(LoginRequiredMixin, ListView):
    template_name = 'main_category/all_main_categories.html'
    model = MainCategory


class MainCategoryUpdate(PermissionRequiredMixin, UpdateView):
    template_name = 'main_category/main_category_update.html'
    form_class = MainCategoryForm
    model = MainCategory
    permission_required = 'webapp.change_maincategory'

    def get_success_url(self):
        return reverse('webapp:main_category_view', kwargs={'pk': self.object.pk})


class MainCategoryDelete(PermissionRequiredMixin, DeleteView):
    template_name = 'main_category/delete_main_category.html'
    model = MainCategory
    success_url = reverse_lazy('webapp:main_categories_view')
    permission_required = 'webapp.delete_maincategory'

source/webapp/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Issue Task{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body style="background-image: url({% static 'image/aifon_wite.jpg' %})">
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="text-white text-center px-3" href="/admin/">Admin</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% if user.is_authenticated %}
                    {% block menu %} {% endblock %}
                        <a class="text-white text-center px-3" href="{% url 'accounts:detail' request.user.pk %}">Hi {{ request.user.username }}</a>
                        <a class="text-white text-center px-3" href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">Logout</a>
                        <div class="dropdown">
                        <button class="btn btn-primary text-white dropdown-toggle" type="button"
                            id="about-us" data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">Look all...</button>
                        <div class="dropdown-menu" aria-labelledby="about-us">
                            <a class="dropdown-item" href="{% url 'webapp:articles_view' %}">Articles</a>
                            <a class="dropdown-item" href="{% url 'webapp:main_categories_view' %}"> Main Category</a>
                            <a class="dropdown-item" href="{% url 'webapp:categories_view' %}">Category</a>
                            <a class="dropdown-item" href="{% url 'accounts:users' %}">Users</a>
                        </div>
                    </div>
                    <div class="dropdown">
                        <button class="btn btn-primary text-white dropdown-toggle" type="button"
                        id="new" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">Create...</button>
                        <div class="dropdown-menu" aria-labelledby="new">
                            <a class="dropdown-item"  href="{% url 'webapp:article_create' %}">Write article</a>
                            <a class="dropdown-item"  href="{% url 'webapp:category_create' %}">New category</a>
                            <a class="dropdown-item"  href="{% url 'webapp:main_category_create' %}">New Main category</a>
                        </div>
                    </div>
                {% else %}
                    <a class="text-white text-center px-3" href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">Login</a>
                    <a class="text-white text-center px-3"href="{% url 'accounts:create' %}?next={{ request.get_full_path }}">Sing Up</a>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container mt-sm-5 p-md-3">
        {% block content  %}
            
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script type="application/javascript" src="{% static 'js/bootstrap.bundle.js' %}"></script>
</body>
</html>